{% set xorg_name = "server" %}
{% set xorg_category = "xserver" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.19.3" %}
{% set sha256 = "677a8166e03474719238dfe396ce673c4234735464d6dadf2959b600d20e5a98" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - python  # [win]
    - toolchain
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - xorg-util-macros
    - mesalib
    - xorg-applewmproto
    - xorg-bigreqsproto
    - xorg-damageproto
    - xorg-fixesproto
    - xorg-fontsproto
    - xorg-glproto
    - xorg-inputproto
    - xorg-presentproto
    - xorg-randrproto
    - xorg-recordproto
    - xorg-renderproto
    - xorg-resourceproto
    - xorg-scrnsaverproto
    - xorg-videoproto
    - xorg-xcmiscproto
    - xorg-xproto
    - xorg-xextproto
    - xorg-xineramaproto
    - xorg-xtrans
    - xorg-util-macros
    - xorg-font-util
    - pixman
    - xorg-libx11
    - xorg-libxfont2
    - xorg-libxkbfile
    - xorg-libxfixes
    - xorg-libapplewm  # [osx]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - pixman
    - xorg-libx11
    - xorg-libxfont2
    - xorg-libxkbfile
    - xorg-libxfixes
    - xorg-libapplewm  # [osx]

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org X server'

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
