{% set xorg_name = "libAppleWM" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.4.1" %}
{% set sha256 = "5e5c85bcd81152b7bd33083135bfe2287636e707bba25f43ea09e1422c121d65" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not osx]

requirements:
  build:
    - pkg-config
    - toolchain
    - xorg-util-macros
    - xorg-applewmproto
    - xorg-libx11
    - xorg-xextproto
    - xorg-libxext
    - pthread-stubs
    - xorg-libxcb

  run:
    - xorg-libx11
    - xorg-libxext
    - xorg-libxcb

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: |
    AppleWM is a simple library designed to interface with the Apple-WM extension.
    This extension allows X window managers to better interact with
    the Mac OS X Aqua user interface when running X11 in a rootless mode.

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
